[package]
name = "infrabase"
version = "0.1.0"
authors = ["Ivan Kozik <ivan@ludios.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.5.0"
diesel = { version = "1.0.0", features = ["postgres", "chrono", "network-address"] }
ipnetwork = "0.13.0"
dirs = "2.0"
dotenv = "0.9.0"
chrono = "0.4.7"
structopt = "0.3.0"
log = "0.4.7"
env_logger = "0.7.0"
indoc = { version = "0.3.3", features = ["unstable"] }
itertools = "0.8.0"
# Upstream stopped development
natural_sort = { git = "https://github.com/ludios/natural-sort-rs", rev = "d784c63b299ff1b6ea346a2536fadff22c73fc78" }
tabwriter = "1.1.0"
bstr = "0.2.8"
termcolor = "1.0.5"
runtime-fmt = "0.4.1"
# New unreleased changes
salsa = { git = "https://github.com/salsa-rs/salsa", rev = "e1f6572a007d6733be4a52eabd0e94bcef435415" }
