[package]
name = "infrabase"
version = "0.1.0"
authors = ["Ivan Kozik <ivan@ludios.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.5.0"
diesel = { version = "1.0.0", features = ["postgres", "chrono", "network-address"] }
ipnetwork = "0.13.0"
dirs = "2.0"
dotenv = "0.9.0"
chrono = "0.4.7"
structopt = "0.3.0"
log = "0.4.7"
env_logger = "0.6.2"
indoc = { version = "0.3.3", features = ["unstable"] }
itertools = "0.8.0"
natural_sort = { git = "https://github.com/ludios/natural-sort-rs" }
tabwriter = "1.1.0"
runtime-fmt = "0.4.0"
bstr = "0.2.8"
